### ISSUE TITLE
Add Link to VS.Squirrel in docs

### ISSUE THREAD

**Issue by ChrisPulman** [clowd/Clowd.Squirrel#102]
VS.Squirrel is a Visual Studio add-in for building Squirrel installers

https://github.com/ChrisPulman/VS.Squirrel
Try it, if you like it kindly add to your documentation, otherwise please close this.
Many thanks.

NOTE: you must use the following Project tags or set the properties in your assembly
```
    <Version>x.x.x</Version>
    <Description>Product description</Description>
    <Company>Your Company</Company>
    <Authors>Your Name</Authors>
```
https://www.vsixgallery.com/extension/VS.Squirrel.Chris.Pulman.b619c884-a2aa-4750-8433-bdca671f6d26/

You will find it in: View - Other Windows - SquirrelPackager
You can configure the Options with: Tools - Options - VS.Squirrel

**Comment by caesay** [comment]
@ChrisPulman I think it would make a lot more sense for this functionality to be provided by Squirrel in the form of custom msbuild targets and/or roslyn analysers that ship with the NuGet Package. Therefore everyone using VS could benefit from enhanced integration without needing to install a VS extension. 

It could be that Squirrel provides additional properties (eg. `<SquirrelBuildOnPublish>true</SquirrelBuildOnPublish>`) that could be easily added to people's csproj after installing the NuGet Package.

Is this something you would be willing to take a look at? If not, I will close this issue.
