### ISSUE TITLE
Error code 17 when installing

### ISSUE THREAD

**Issue by 2899193288** [clowd/Clowd.Squirrel#106]
After released, I double click my AppSetup.exe.Then, an error message box displayed.
![屏幕截图 2022-08-17 170013](https://user-images.githubusercontent.com/31467903/185079410-9524a2da-ba4a-4d29-98ba-8626f89215d9.jpg)

**Comment by 2899193288** [comment]
Clowd.Squirrel version 2.9.40

**Comment by caesay** [comment]
Hi, this looks like your AppSetup.exe may be corrupt / not created properly. Can you please provide instructions to reproduce the issue, or even upload a broken Setup.exe file so that I can check it?

**Comment by 2899193288** [comment]
AppSetup.exe may be ok,because I can install successfully on one computer.But another fails.

**Comment by caesay** [comment]
What is the windows username on the computer that fails? does it have unicode characters? If so, please update to 2.9.42 as it contains fixes for computers that have unicode in windows username.

**Comment by 2899193288** [comment]
This may be the reason.I will update to 2.9.42 and try again.
