### ISSUE TITLE
Registry is not updated after Update?

### ISSUE THREAD

**Issue by chrisdecker1201** [clowd/Clowd.Squirrel#108]
Hello,

currently I'm using version 2.9.42 and discovered the issue that the registry entry after an update is not updated.

When I install a 0.1.254 and update this with a 1.0.8 version my application is updated just fine and everything is working, but when I look in the registry and especially in the Apps & Programs Windows dialog I see the old 0.1.254 version.

Expected behavior:

Update every relevant registry entry (these are the two which are wrong for me): 

* DisplayVersion
* DisplayIcon
* ...

Kind regards,

Christian

**Comment by caesay** [comment]
Can you check if this value has been updated in the registry by using `regedit.exe` please?

**Comment by caesay** [comment]
Also please confirm if you are using the `UpdateApp();` helper to install updates for your app (as this automatically calls `CreateUninstallerRegistryEntry()` to update the registry entry.) If you are not using the former you will need to call the latter manually.

**Comment by chrisdecker1201** [comment]
Okay. That was the case. We do not use the `UpdateApp();`. Thank you for the quick response.

I really like this tool :)

**Comment by Rob-Post** [comment]
I think the comment for `UpdateApp()` is not complete. It doesn't mention it also calls `CreateUninstallerRegistryEntry()`
