### ISSUE TITLE
could we run installer silently?

### ISSUE THREAD

**Issue by shengxue** [clowd/Clowd.Squirrel#114]
could we run installer silently?

**Comment by caesay** [comment]
There is not a way currently to receive the --silent argument in `HandleEvents`. If the installer is in silent mode, `OnAppInstall` will execute during install, but `OnAppRun` will not run. 

If the installer is in regular (not silent) mode, OnAppRun will also be run.

**Comment by shengxue** [comment]
@caesay ```OnAppInstall``` should not show dialog if the installation is in silent mode, so this info is very important.

**Comment by caesay** [comment]
It is very important that OnAppInstall _never_ shows any dialogs. Squirrel executes this while your app is being installed, and it expects your application process to exit within 15 seconds. `HandleEvents` will do this automatically (execute the delegate, and then exit the process).

**Comment by shengxue** [comment]
@caesay I thought that in ```OnAppInstall``` I can install some 3rd party software that my app depends on.    Any suggestion how to install 3rd party softwares with Squirrel in similar way as installing .net/vcruntime?

**Comment by caesay** [comment]
Unfortunately, this is not currently possible during Squirrel install. You could install the software the first time your app runs (eg. `OnAppRun` where firstRun is true).

**Comment by shengxue** [comment]
@caesay  but ```OnAppRun``` will not run in silent mode. :(  It means the 3rd party software can not be installed in silent mode.

**Comment by caesay** [comment]
Right, because your app will not be started in silent mode after install. The only approach I can think of would be to use OnAppRun to detect whether the 3rd party software is installed or not, and if it is not installed - ask the user at every launch if they would like to install it. Or preferably, bundle the required 3rd party components with your app.

**Comment by shengxue** [comment]
@caesay  what do you mean by 'bundle the required 3rd party components with your app'? could you please give me more details about this solution? many thanks!

**Comment by shengxue** [comment]
@caesay  do you have plan to let ```HandleEvents``` know if it is in silent mode? or run ```OnAppRun``` in silent mode?
