### ISSUE TITLE
could we stop the installation from onInitialInstall?

### ISSUE THREAD

**Issue by shengxue** [clowd/Clowd.Squirrel#115]
could we stop the installation from ```onInitialInstall```?  For example, when ```onInitialInstall``` detects that the installer does not run as administrator, and like to stop the installation.

**Comment by caesay** [comment]
No, this is not possible. `onInitialInstall` is already too late, the install is finished and that is the last step.

Furthermore, Squirrel should not be run as administrator (there used to be a check _preventing_ this from happening). It is not designed to install third party components or windows services. It is not designed to be installed into any location which requires administrator access, or support any application which requires administrator access. I don't plan to support any of these requirements, and if this is something you need you should:
 - build this logic into your application start-up
 - fork Squirrel 
 - look for an alternative installer like WiX which supports these scenarios.
