### ISSUE TITLE
Shortcuts are missing after installing

### ISSUE THREAD

**Issue by tcsidevtools** [clowd/Clowd.Squirrel#117]
Hello, 

I've noticed a possible issue with the MSI Deployment tool that squirrel can generate. It does appear to install the application correctly on user switch. But shortcuts are not generated correctly.

The hooks in our application will generate a shortcut OnAppInstall to the StartMenu.

**Comment by caesay** [comment]
> But shortcuts are not generated correctly.
Can you elaborate? What is not correct? What version of Squirrel
