### ISSUE TITLE
Installed application Start Menu Folder

### ISSUE THREAD

**Issue by chrisrestall** [clowd/Clowd.Squirrel#118]
When installing our application via a packed exe, it shows up in the start menu under "Microsoft".  Full path:

C:\Users\me\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Microsoft

Looking through the old squirrel issues, it looks at though it should show up under a company_name folder, assumed thats the value of "packAuthors" parameter specified in the squirrel.exe pack command. 
 We are specifying a company name but it still dumps under "Microsoft"

**Comment by caesay** [comment]
What version of Squirrel are you using?

### v2
The behavior in v2 when creating shortcuts into the "StartMenu" location would be to take the company name from the PE metadata (version info table). This is identical to the older Squirrel.Windows. If you hover over your exe file in Explorer you can see what this is set to. 
![image](https://user-images.githubusercontent.com/1287295/189450519-1a9d6b5f-1320-473d-9cef-cebb03c97e59.png)
If there is no company name set in the PE metadata, it will use the package author.

### v3
The behavior in v3 is to always use the package author property and ignore the PE metadata. It does not matter if the company name/publisher is set on the PE file.
