### ISSUE TITLE
NuGet pack fails when Squirrel is called from MsBuild

### ISSUE THREAD

**Issue by xanderio** [clowd/Clowd.Squirrel#12]
I'm calling `Squirrel` via this `msbuild` target. The `Squirrel http-down` command works fine however the `Squirrel pack` command produces the error message i included below. 

A quick internet search revealed that this is error message is from `nuget` complaining about `$PATH`, i check `$PATH` multiple time and spotted nothing unusual. 

The strangest thing is that when i copy the command that `msbuild` executes and call it manually it just works. 
 
Msbuild target:
```
  <Target Name="Package" AfterTargets="Publish" Condition=" '$(Configuration)' == 'Release' ">
    <PropertyGroup>
      <PackageDir>$(MSBuildProjectDirectory)\Packages\</PackageDir>
      <cs_PublishDir>$(MSBuildProjectDirectory)\$(PublishDir)</cs_PublishDir>
      <Squirrel>$(PkgClowd_Squirrel)\tools\Squirrel</Squirrel>
    </PropertyGroup>

    <Exec Command="$(Squirrel) http-down --url=http://update-server.com/updates/package --releaseDir=$(MSBuildThisFileDirectory)Releases\ " />
    <Exec Command="$(Squirrel) pack --packName=package --packVersion=$(Version) --packAuthors=company --packDirectory=&quot;$(cs_PublishDir) &quot; --splashImage=.\installdisk.gif --framework=net5 --releaseDir=&quot;$(MSBuildThisFileDirectory)Releases&quot;"/>

  </Target>
```

Squirrel pack error:
```
[ERRO] System.Exception: Failed nuget pack (exit 1): 
   Illegal characters in path.
     at SquirrelCli.Program.Pack(PackOptions options)
     at SquirrelCli.CommandAction`1.Execute(IEnumerable`1 args)
     at SquirrelCli.CommandSet.Execute(String[] args)
     at SquirrelCli.Program.Main(String[] args)
```

Squirrel pack command called by msbuild:
```
.nuget/packages/clowd.squirrel/2.6.2-pre/tools/Squirrel pack --packName=package --packVersion=10.3.0 --p
ackAuthors=company --packDirectory=bin/Release/net5.0-windows/publish --splashImage=installdisk.gif --framework=net
5 --releaseDir=Releases
```

**Comment by caesay** [comment]
Hi, I suspect the `--packDirectory` path is getting mangled by msbuild. Can you add the following line to your msbuild task and see what it prints?

`<Message Importance="High" Text="&quot;$(MSBuildThisFileDirectory)Releases&quot;" />`

**Comment by xanderio** [comment]
Here is the output you ask for.
```
"C:\Users\xanderio\Projects\package\PackageTool\bin\Release\net5.0-windows\publish\ "
```

**Comment by caesay** [comment]
It looks like this is caused by how windows parses command line arguments - described here https://devblogs.microsoft.com/oldnewthing/?p=12833

Squirrel removes that trailing space, so `"C:\Users\xanderio\Projects\package\PackageTool\bin\Release\net5.0-windows\publish\"` is what gets sent to Nuget on the command line - but `\"` produces an escape sequence causing the trailing double quote to become part of the path.

A short-term workaround would be to remove the trailing slash from the path being sent to Squirrel. I will look to fix this in the next version.

**Comment by xanderio** [comment]
I was able to get this working by using `$(PublishDir.TrimEnd('\'))` for now.
