### ISSUE TITLE
Upgrade leaves old versions

### ISSUE THREAD

**Issue by cupper1** [clowd/Clowd.Squirrel#125]
Following all the examples, I have managed to create delta updates and deploy them. In my test area I have a standard windows 10 VM. I install my application and then upload the delta package.
On the next run the application sees the update, runs it, application updates. This is good except for two things:
1. It doesn't consider the application.config file that the application creates when starting (so app seems to be "fresh") how would I keep this file in the new version folder?
2. The old version is still there, taking up double the room. Is there a function to tell clowd.Squirrel to remove the old version?

BTW, thank you for this project and your consistent feedback and support!

**Comment by caesay** [comment]
You can not store any files in your application directory that you expect to need in the next version. You can store that file (application.config) anywhere else you'd like. Roaming app data, one folder up, whatever.

Squirrel always keeps the last version around, this is working as intended https://github.com/clowd/Clowd.Squirrel/issues/64
