### ISSUE TITLE
Saving files on update

### ISSUE THREAD

**Issue by cupper1** [clowd/Clowd.Squirrel#127]
Hello
I have this all running really well from an s3 bucket. I have a few beta users running it and they are reporting that config files aren't staying with the upgrade.
For example we have a config file that is written to after the file runs the first time. When the upgrade happens this file is deleted. before I try to handle this scenario in code, is there a helper or something that we can call to allow these files to persist?
(We have 2 of them and know the exact filename and subfolder)
Thanks!

**Comment by remco1271** [comment]
See Squirrel#198 for more information.

**Comment by caesay** [comment]
Just to summarise, the application directory gets entirely replaced on update. You should not modify the files in this directory as any changes will be lost. You might consider storing your settings to the roaming app data (eg. `%appdata%\yourapp`) instead of inside your app directory.
