### ISSUE TITLE
My app is Squirrel aware even tho it shouldn't be

### ISSUE THREAD

**Issue by nazar322** [clowd/Clowd.Squirrel#130]
How come my app is Squirrel aware even tho I don't have `<SquirrelAwareVersion xmlns="urn:schema-squirrel-com:asm.v1">1</SquirrelAwareVersion>` in the manifest file, nor I have relative attribute in AssemblyInfo.cs, I even removed all usages of Squirrel related code, only the package included.

`[INFO] Program: There are 1 SquirrelAwareApp's. Binaries will be executed during install/update/uninstall hooks.`

I'd like to use command args events, not the SquirrelAwareApp's ones.

**Comment by caesay** [comment]
Hi, please share the version of Clowd.Squirrel you're using. Also the command line arguments you are using to create your releases. There are a number of ways that your app can be detected as SquirrelAware (including adding the `-e your.exe` argument).

If your app is SquirrelAware, it will get executed at certain points with squirrel specific command line arguments (eg. `--squirrel-install`). You can use the `SquirrelAwareApp` class to automatically handle these events in a C# app, or you can ignore this class and handle them yourself.
