### ISSUE TITLE
Prevent installation if operating system version is not supported

### ISSUE THREAD

**Issue by RusselRillema** [clowd/Clowd.Squirrel#131]
In my csproj file and in my nupkg file I've specific the TFM as net6.0-windows10.0.17763.0
When trying to run this on a windows 8.1 machine, for example, the install runs and I get a missing dll exception when the app tries to run.
Is there some way to prevent the install (with a nice error message explaining their OS is not supported). Or perhaps is there an option to  give an error on app startup? (I did open a SO question about that option but unfortunately didn't get an responses).
For reference [here](https://stackoverflow.com/questions/74472728/give-custom-error-when-target-framework-is-not-met) is the SO question

Any ideas or guidance would be greatly appreciated :)

**Comment by caesay** [comment]
This is not possible at the moment, but it's something I'm currently working on for the next v3 release!

**Comment by RusselRillema** [comment]
Oh wow, that's great news! 
Thanks so much

Do you know when v3 will have a stable release? Not to apply any pressure, just wondering if we looking at days, months, years?

**Comment by caesay** [comment]
I use v3 in my own applications (so it does work), but it's likely to change quite a bit before it's "stable". 6 months at least.

**Comment by RusselRillema** [comment]
Cool, thank you! Appreciate the feedback :)

**Comment by caesay** [comment]
I'm going to re-open to track the "Prevent installation if target framework is not met" feature. Will close once this has been released.

**Comment by caesay** [comment]
Added in v4
