### ISSUE TITLE
ESET NOD32 suddenly detecting ML/Augur trojan in Update.exe

### ISSUE THREAD

**Issue by m-chandler** [clowd/Clowd.Squirrel#132]
Feel free to close this issue if not appropriate; I thought I would create it for visibility / discussion / anyone else that encounters this issue.

It would appear that within the last 24 hours ESET / NOD32 has started detecting an ML/Augur trojan within Update.exe.

This results in the file being deleted and auto updates are broken.

Only two vendors on VirusTotal detect problems in this file.
https://www.virustotal.com/gui/file/26a2d9a2d7608fc8f3d9e5b6694940e87fb8105278d03a0f3d34e3cf5805fde5/detection

This has broken the update procedure for our apps. 

I have submitted Update.exe from the 2.9.42 NuGet package to NOD32 for analysis.

**Comment by caesay** [comment]
Hi, I'm sorry to hear this has broken your updates. I've had some reports from my own users of this also. Unfortunately the best advice I can give is to code-sign your application and read https://github.com/clowd/Clowd.Squirrel/issues/28
