### ISSUE TITLE
Include support for .NET 7

### ISSUE THREAD

**Issue by Segergren** [clowd/Clowd.Squirrel#134]
Hi, would be awesome if you could upgrade the "--framework" .NET version to net7.

**Comment by caesay** [comment]
I have tested, this is working fine in both maintained versions of Clowd.Squirre - 2.9.42 and 3.0.210. If you are already on the latest 2.x or latest 3.x version and are still having problems, please share your version, your command line instructions for triggering a release, and the error returned by Squirrel
