### ISSUE TITLE
Gist for Publish / Deployment of Cloud Squirrel 3.0 to Azure Storage with Github Actions

### ISSUE THREAD

**Issue by aherrick** [clowd/Clowd.Squirrel#139]
I wanted to share a simple Gist I put together with Github Actions to package/deploy/release my App with Clowd 3.0

Hopefully it helps someone!

https://gist.github.com/aherrick/64bfd7c7f063d4dc9eb461e248967e65

**Comment by caesay** [comment]
There is now GH actions documentation in Velopack
