### ISSUE TITLE
AppSettings.json changes lost after update

### ISSUE THREAD

**Issue by jonchicoine** [clowd/Clowd.Squirrel#140]
Am i missing something? If changes are made to a config file like AppSettings.json to change logLevel or to store the machine name of where the server can be found in client/server env., is there anyway to preserve the changes so they are not lost during an update?

It seems like every app would need to preserve deployment specific env sittings (like things stored in appSettings.json.

Is there a way to do this?

thanks
jonathan

**Comment by caesay** [comment]
You can not store files in your application directory, and should not modify any files in your application folder either. Typically  for end user applications you would store your settings in roaming app data which will follow the user around if they are using various domain joined computers, while Squirrel installs the application to local app data.
