### ISSUE TITLE
Question:  About Github Releases

### ISSUE THREAD

**Issue by testpossessed** [clowd/Clowd.Squirrel#143]
May seem like a stupid question, but the documentation is not 100% clear to me.

When I create an update release in Github do I need to include all previous NuGet packages or just the latest full and delta packages along with the setup executable and the RELEASES file.

Thanks in advance of response.

**Comment by caesay** [comment]
Your GitHub release assets should contain: 
- Latest full package
- Latest delta package
- RELEASES file containing lines only for these two packages
- Setup.exe / Setup.pkg

If you are using v3, there is an automated deployment command which can create a draft GitHub release and upload everything for you in the proper configuration.

**Comment by mehmetdrnmrkt** [comment]
I was thinking about this question too.
I'm currently experimenting with a test application. With each new update, I delete the releases file and releasify it. Something like this comes out.
![Ekran görüntüsü 2023-11-21 144148](https://github.com/clowd/Clowd.Squirrel/assets/114909797/7d1303cc-7456-49a3-8294-fc6acd7db0a0)
As far as I've observed, it doesn't cause any problems right now.
Will it cause any problems if I use it this way or will it cause me to lose anything?
