### ISSUE TITLE
Windows uninstaller shows wrong version

### ISSUE THREAD

**Issue by sebaJoSt** [clowd/Clowd.Squirrel#145]
Hey, really love what you are doing here.  I'm on 3.0.210-g5f9f594 and Installing and updating and everything works smooth.

I just noticed that version number in Windows 10 Apps & Features is not updated. Instead the version number of first installed version is shown. Is that intentional?

Kind regards

**Comment by Rob-Post** [comment]
If you don't use `UpdateApp()` then you should also call `CreateUninstallerRegistryEntry()`; see #108

**Comment by sebaJoSt** [comment]
Indeed I was not using `UpdateApp()`. I call `CreateUninstallerRegistryEntry()` now before restarting the app and registry entry was updated. The issue can be closed.
