### ISSUE TITLE
MSI contains unsigned setup

### ISSUE THREAD

**Issue by llehn** [clowd/Clowd.Squirrel#149]
I'm trying to create an MSI with this command line:

`csq pack -u MyApp -p dist --noDelta -r releases -e MyApp.exe -v $prodImageVersion -i icon.ico -msi x64 -n "/a /p $password /f $certFile /fd sha256 /tr http://timestamp.digicert.com /td sha256"`

Output: 
* MyApp.exe is signed,
* MyAppSetup.exe is signed
* MyApp_DeploymentTool.msi which contains the setup, named MyApp.exe - which is unsigned.

I'm using version 3.0.210-g5f9f594

**Comment by caesay** [comment]
Will be fixed in the next v3 release
