### ISSUE TITLE
SquirrelAwareVersion Side-By-Side error

### ISSUE THREAD

**Issue by mitjaahlin** [clowd/Clowd.Squirrel#15]
After successful packing of the application. I'm experiencing an install error.

Error in /SquirrelTemp/Squirrel-Install.log:
error: ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\mitja\AppData\Local\GBot\app-0.4.4\GBot.exe: System.ComponentModel.Win32Exception (14001): An error occurred trying to start process 'C:\Users\mitja\AppData\Local\GBot\app-0.4.4\GBot.exe' with working directory 'C:\Users\mitja\AppData\Local\SquirrelTemp'. The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

Error in EventViewer:
Activation context generation failed for "C:\Users\mitja\AppData\Local\GBot\app-0.4.4\GBot.exe".Error in manifest or policy file "C:\Users\mitja\AppData\Local\GBot\app-0.4.4\GBot.exe" on line 3. The element SquirrelAwareVersion appears as a child of element urn:schemas-microsoft-com:asm.v1^assembly which is not supported by this version of Windows.

The same application was installed successfully using previous release.

Content of GBot.manifest:
```<?xml version="1.0" encoding="utf-8"?>
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1">
  <assemblyIdentity version="0.4.4.0" name="GBot.App"/>
  <SquirrelAwareVersion>1</SquirrelAwareVersion>
</assembly>´

**Comment by caesay** [comment]
I believe this is an issue with the documentation. Please revise your manifest to include the SquirrelAwareVersion namespace: 

`<SquirrelAwareVersion xmlns="urn:schema-squirrel-com:asm.v1">1</SquirrelAwareVersion>`

**Comment by mitjaahlin** [comment]
It works now. Thanks!
