### ISSUE TITLE
Release 2.9.48 is broken

### ISSUE THREAD

**Issue by Noah1989** [clowd/Clowd.Squirrel#158]
I see that it has already been retracted from NuGet due to "critical bugs": https://www.nuget.org/packages/Clowd.Squirrel/2.9.48

Unfortunately it took me some time to figure out what happened. That's why I'd like to open this issue so that anyone unlucky enough to have upgraded to that version during the timeframe it was online can find out what's going on.

The error I got was: Failed to initialize CoreCLR (-2147450743)

**Comment by caesay** [comment]
As you mentioned, the release has been deprecated. I will leave this issue open until I release a new version.

**Comment by luislhg** [comment]
@caesay do you happen to know which commit broke 2.9.48?
