### ISSUE TITLE
Enforced elevated permissions for setup executable

### ISSUE THREAD

**Issue by mateuszbendkowski** [clowd/Clowd.Squirrel#162]
Hi,
is there a way to enforce the Clowd.Squirrel to use the manifest file for the setup executable itself? What I want to achieve is the setup which will always ask to run with elevated permissions - to not ask user many times for each prerequisite item. All works fine if setup is run with elevated permissions manually. I would like to have setup, which will ask for elevated permissions. Any hint?

Regards,
Mateusz

**Comment by caesay** [comment]
It's not supported to run Squirrel with elevated permissions.
