### ISSUE TITLE
Shortcut names for different environments

### ISSUE THREAD

**Issue by RichardSinden** [clowd/Clowd.Squirrel#164]
I have an app that I deploy with different environments (e.g. test, prod, etc.). The app only gets built once and for each environment deploy, the app.config is updated with different service addresses and .nuspec files are updated with a different id/title and it is repackaged.
At the moment, because these two versions have the same VersionInfo.ProductName, then the shortcut is called the same thing, which makes it difficult to differeniate them in the Start Menu. 
Looking at the code ([UpdateManager.linkTargetForVersionInfo](https://github.com/clowd/Clowd.Squirrel/blob/289867fbba9222e80d0f20b2d37ddbe2fa32a13e/src/Squirrel/UpdateManager.Shortcuts.cs#L127)), it appears that the version info productName is prefered over the package.
`var possibleProductNames = new[] {
                versionInfo?.ProductName,
                package.ProductName,
                versionInfo?.FileDescription,
                Path.GetFileNameWithoutExtension(exeName),
            };`

I'd like to add an option to prefer the package ProductName, perhaps by adding `, bool preferPackageProductName = false` to the [CreateShortcutsForExecutable ](https://github.com/clowd/Clowd.Squirrel/blob/289867fbba9222e80d0f20b2d37ddbe2fa32a13e/src/Squirrel/UpdateManager.Shortcuts.cs#L17) method (and corresponding RemoveShortcutsForExecutable). 

I'm happy to create a PR. Any thoughts/issues with this?

**Comment by caesay** [comment]
Please see my comments on your pull request, there are several ways to do this already without a breaking change to the entire API surface.
