### ISSUE TITLE
Basic HTTP Authentication

### ISSUE THREAD

**Issue by dloez** [clowd/Clowd.Squirrel#165]
I was wondering if there are any reasons behind not implementing at least basic HTTP Authentication with an extra argument when calling the CLI with the `http-down` command. This would allow, for example, a user to use Nexus as its source for the releases folder while keeping the Nexus anonymous access disabled.

If there are no specific anti-design patterns on this feature, would you be interested in receiving a simple PR with the changes required?

**Comment by caesay** [comment]
Hi, I have not tried it, but does the following syntax work? `http://username:password@example.com/` If it does not currently work - I would accept a PR which fixes this. I am not sure that more cli arguments are needed to support this.

**Comment by caesay** [comment]
Future issues / feature requests should be sent to the Velopack repository.
