### ISSUE TITLE
Firewall prompt

### ISSUE THREAD

**Issue by mariopasquali** [clowd/Clowd.Squirrel#166]
Hi all,

This is more of a question than an issue, but does the use of Junctions (#24) help avoid the firewall prompt on updates for the most of you?

I have been experimenting with Junctions before integrating Clowd.Squirrel, and as far as I can see, the Windows Firewall considers the target path of the junction (not the junction path itself), which defeats the use of junctions for this purpose.  Conceptual steps to reproduce:

- copy app to `\myapp\v1.0`
- make junction `\myapp\current` to `\myapp\v1.0`
- start app from `\myapp\current\app.exe` -> firewall prompt for `\myapp\v1.0\app.exe` (instead of `\myapp\current\app.exe`)
- copy new app to `\myapp\v1.1`
- update junction `\myapp\current` to `\myapp\v1.1`
- start app from `\myapp\current\app.exe` -> firewall prompt for `\myapp\v1.1\app.exe`

I can see from the app logs that it considers itself running from `\myapp\current` as expected.  I can also see that Windows Firewall added a rule based on the target path, not the junction path. 

Am I missing something?

Thank you for your help,
Mario

**Comment by caesay** [comment]
I am not 100% sure, however v3 does not use junctions or symbolic links. Instead, v3 uses a regular `current` folder, and the application files are moved in and out of this folder. Therefore it does solve the firewall problem, and other problems mentioned in the linked issue.
