### ISSUE TITLE
Why is Clowd.Squirrel Deprecated on NUGet and Will it Return?

### ISSUE THREAD

**Issue by LouDavis951** [clowd/Clowd.Squirrel#168]
I was experimenting in using Clowd.Squirrel for a .NET 6.0 Winform application.  This morning I saw that NuGet had flagged this package as deprecated for critical bugs.  Will these issues be resolved or is this the end of Clowd.Squirrel?

**Comment by caesay** [comment]
No, I'm still working on this project (hence the recent release) but some personal life issues have slowed my time available. I'm working on getting some updates out to v2 and v3 very soon. Thanks
