### ISSUE TITLE
The process cannot access the file 'folder name' when trying to install/update via full installer

### ISSUE THREAD

**Issue by luislhg** [clowd/Clowd.Squirrel#170]
Hello, I'm having a issue where the full installer is saying "The process cannot access the file" and I end up with a blank folder and I lose my old installation and the new one.

**Error**
![Squirrel Report](https://github.com/clowd/Clowd.Squirrel/assets/16278387/7e2a4029-415b-4495-bf63-7fbb4cfbe5cf)

**Result**
![Squirrel app folders](https://github.com/clowd/Clowd.Squirrel/assets/16278387/1c5b8f59-d9f4-4424-b6a9-8fcbdc8bfb5e)

**Log**
The log contains the installation of version 8.0.1 which worked, and then the "attempt" to install 8.0.2 with the exceptions.
[Squirrel-bug-censored.log](https://github.com/clowd/Clowd.Squirrel/files/12113143/Squirrel-bug-censored.log)

**Repro steps**
1) Install 8.0.1 via Full Installer
2) Open 8.0.1 software
3) The software will try to download 8.0.2 Full Installer and run it (`Process.Start("MyInstaller.8.0.2.exe")`)
4) Exception/invalid install as reported above

_Note¹: I'm not using the SDK to detect/update. My user has 8.0.1 installed and the software just downloads and runs the latest full installer (8.0.2 in this case)._
_Note²: It used to work fine with .NET 4.8 and original Squirrel._
_Note³: In step 3, I already tried to run a .bat file and close the software. The bat waits for 5 seconds and then runs the installer, there was no process in use when the 8.0.2 installer opened, it still failed with the same exception/error._

---
Not sure why/how but the only situation where it works is if
1) 8.0.1 is opened and running but does not download/install 8.0.1
2) User manually downloads and runs 8.0.2 installer
3) 8.0.2 installer shut down the running app (forced, as the software did not log it was closing) and 8.0.2 is correctly installed.

This is unexpected though. If my software is properly closed and not running, why would a new version full installer fail to install?

**Comment by KennyTK** [comment]
Could you provide a code snippet of your .bat file? I want to better understand what you're doing

**Comment by luislhg** [comment]
Found the issue, it's how Process.Start / ProcessStartInfo is implemented differently in .NET 6.
In .NET 6 I now need to set the WorkingDirectory, otherwise it locks itself to the parent process folder by default.
e.g.: WorkingDirectory = System.IO.Path.GetDirectoryName(processPath)

I'm closing the issue as this is not related to Squirrel.
