### ISSUE TITLE
Did the installer detect that the version being installed is an old version?

### ISSUE THREAD

**Issue by danilobreda** [clowd/Clowd.Squirrel#171]
If my customer has a version 1.5 installed and for some reason reexecute the 1.4 version installer.
How can i detect it to block that operation?

**Comment by Noah1989** [comment]
Currently the setup .exe always just overwrites everything without any way to intercept programatically, see this releated issue: https://github.com/clowd/Clowd.Squirrel/issues/70

**Comment by KennyTK** [comment]
A workaround could be checking for most recent version on app start. This would be inconvenient for person accidentally running old installer but experience is the best teacher.

**Comment by caesay** [comment]
It's not possible, as people have mentioned, the installer currently always overwrites the installed app. I do not know when this will be implemented but there are some ideas discussed here https://github.com/clowd/Clowd.Squirrel/issues/70
