### ISSUE TITLE
Win32splash renders in wrong location

### ISSUE THREAD

**Issue by KennyTK** [clowd/Clowd.Squirrel#173]
My screen dimensions are 1366 x 768
![image](https://github.com/clowd/Clowd.Squirrel/assets/16214078/6328a304-4374-491e-94e8-903096966cac)

splash screen image:  620 x 135

squirrel.log with 2nd monitor plugged in:
`2023-08-10 20:32:13.4173 [INFO] - User32SplashWindow: Image dpi is 95.9866, screen dpi is 96. Rendering image at [650,512,620,135]`

squirrel.log with only main display:
`2023-06-09 23:27:22.7488 [INFO] - User32SplashWindow: Image dpi is 95.9866, screen dpi is 96. Rendering image at [373,296,620,135]`

It seems like the image position is correct when using one display. When I attach a 2nd display of different dimensions, the splash shifts to the bottom right quadrant of screen. 

I think something weird is happening with MONITORINFO and specifically 
`x = (mi.rcWork.Width - w) / 2;
y = (mi.rcWork.Height - h) / 2;`

x = (1366 - 620) / 2 = 373 =/= 650
y = (768 - 135) / 2 = 316.5 =/= 512

**Comment by caesay** [comment]
Thanks for reporting this, I'll have a look!

**Comment by KennyTK** [comment]
Working on a pr for this!

**Comment by caesay** [comment]
Fixed in v4

**Comment by KennyTK** [comment]
Did you fix by always loading on default display or by enumerating displays?
