### ISSUE TITLE
Progress dialog title has a random process name

### ISSUE THREAD

**Issue by luislhg** [clowd/Clowd.Squirrel#178]
Any way to change this random title "squF8D3.tmp.exe"?
![image](https://github.com/clowd/Clowd.Squirrel/assets/16278387/4fb339a1-446a-4f45-8136-467db1846062)

**Comment by KennyTK** [comment]
I don't think this dialog box is intended function. Could you share a code snippet or example project that causes this to happen?

**Comment by luislhg** [comment]
In Squirrel pack command just add a framework dependency, such as "squirrel pack --framework net6" and make sure to run the installer in a machine that does not have this .NET runtime installed.

Squirrel will open a dialog for each missing dependency/framework that it's installing.

This is the piece of code doing it:
![image](https://github.com/clowd/Clowd.Squirrel/assets/16278387/b0b1b6a1-04b8-45ad-99fc-37f822e103b6)

**Comment by caesay** [comment]
This dialog is only shown if you do not provide a splash image. If you provide your own splash image, this image is shown instead. However, I do think we can improve this dialog.
