### ISSUE TITLE
Tool Squirrel.exe/Update.exe is reported as trojan

### ISSUE THREAD

**Issue by piotrpakula** [clowd/Clowd.Squirrel#183]
Some security vendors report Update.exe and Squirrel.exe files as trojan.
You can check it by uploading file on Virus Total website.
Windows Defender also reports this file as potentially dangerous.

Regars,
Piotr

**Comment by caesay** [comment]
Please refer to https://github.com/clowd/Clowd.Squirrel/issues/28
