### ISSUE TITLE
Code contracts are deprecated and should be replaced

### ISSUE THREAD

**Issue by KennyTK** [clowd/Clowd.Squirrel#185]
### Summary:
- Code contracts have been deprecated and the project is dead.
- Runtime code contracts do not work with VS2017/19.
- Since NET 5+ and since Core 2.0 contracts are not supported.
- Contract coverage is subpar and increasing coverage seems counterproductive given the current state.

What are code contracts?
https://learn.microsoft.com/en-us/dotnet/framework/debug-trace-profile/code-contracts

### Solutions:
1.  [Nullability](https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references) supported since C# 7.0. Replace `Contract.Requires(variable != null);` with ArgumentNullException.ThrowIfNull
2. [system.diagnostics.codeanalysis](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis?view=netcore-3.1) supported in NET core. Compatible with framework but feature essentially not available. Use Postconditions: MaybeNull and NotNull
3. Just remove them because they're clutter.

### Further reading:
[dotnet runtime 23869](https://github.com/dotnet/runtime/issues/23869#issuecomment-415670905)
[stackexchange 47108](https://softwarerecs.stackexchange.com/questions/47108/the-best-code-contracts-alternative-for-vs-2017-2019-and-net-core-projects)
[dotnet roslyn-analyzers 3134](https://github.com/dotnet/roslyn-analyzers/issues/3134)
[nullable-analysis](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis)

**Comment by caesay** [comment]
I remove these and replace with throwing exceptions when I come across them.
