### ISSUE TITLE
Possible to sync AssemblyInfo?

### ISSUE THREAD

**Issue by mikebm** [clowd/Clowd.Squirrel#191]
This is more of a question than an issue.

I'd like to be-able to have the AssemblyInfo.cs file synced with the `packVersion`.
Specifically, `[assembly: AssemblyVersion("1.0")]` 

Is this possible? Or is there a recommended approach to keep these synced together?

thanks.

**Comment by remco1271** [comment]
This is what I have done to get it published.
The powershell script gets the file version and publish it.
Publish is canceled if version already exists.
[remco1271/Clowd.Squirrel.Release](https://github.com/remco1271/Clowd.Squirrel.Release)

**Comment by mikebm** [comment]
> This is what I have done to get it published. The powershell script gets the file version and publish it. Publish is canceled if version already exists. [remco1271/Clowd.Squirrel.Release](https://github.com/remco1271/Clowd.Squirrel.Release)

Ah that's a great idea. Thank you for sharing!
