### ISSUE TITLE
Runtime support for aspnetcore-runtime-8.0.0-win-x86?

### ISSUE THREAD

**Issue by mikebm** [clowd/Clowd.Squirrel#192]
Any chance we can get aspnetcore-runtime-8.0.0-win-x86 and x64 added as framework options?
net8.0-x86 only installs the desktop framework where as my app uses both, the desktop and `aspnetcore-runtime-8.0.0-win-x86`

Thanks.

**Comment by caesay** [comment]
This is already supported. All versions of dotnet core there ever was and ever will be is supported already (in theory). 

Try `--framework net8-x86-asp,net8-x64-asp`.

**Comment by mikebm** [comment]
Thank you, this worked perfectly.  I was looking in Runtimes.cs and didn't notice the -asp option so figured it wasn't supported. Guess I should have dug a little deeper. Thanks for the help! much appreciated.
