### ISSUE TITLE
App only starts after install

### ISSUE THREAD

**Issue by slimshader** [clowd/Clowd.Squirrel#193]
Hi,

trying to package my WPF app with Squirrel and it mostly went smoothly but I am having problem after install, app wont start from the shortcut.

It starts once, right after installation but then after closing, it never starts again when using desktop or start menu icons.

What i've noticed tho is that while my ./releases app has all files in flat structure, after installation therea are 2 exe files: one in root install folder and one inside /app-1.0.0 subdirectory. Both shortcuts point to the root directory exe but have startup folder pointing to app-1.0.0 subfolder. 

When double cliking exe in app-1.0.0 it starts fine tho. Also: exe in root and app-1.0.0 subdir have different sizes (even tho they have same name and icons) so what is this file?

**Comment by caesay** [comment]
The file in the root of your app (`%localappdata%\{yourappid}\{yourexename}.exe`) is an execution stub created by Squirrel. It just runs your app (in `app-1.0.0`) and exits. If there's an issue with this, I'm going to need more info. Can you post a sample app to github? Check event viewer for crashes? Check your `%localappdata%\{yourappid}` for log files/errors? What version of Clowd.Squirrel are you using?

**Comment by slimshader** [comment]
Can't sent the app I am writing about but will try to provide minimal version and the logs

**Comment by slimshader** [comment]
Turns out this issue was different but related: my app was assuring single instance by searching for pre-existing process of the app name but since stub had the same it was always immediately closing assuming that another instance was running. Switched to named mutex-based approach and not it starts fine.

**Comment by caesay** [comment]
Thanks
