### ISSUE TITLE
Github Releases New Update

### ISSUE THREAD

**Issue by mehmetdrnmrkt** [clowd/Clowd.Squirrel#195]
I'm currently experimenting with a test application. With each new update, I delete the releases file and then releasify it. Something like this comes out.

![Ekran görüntüsü 2023-11-21 144148](https://github.com/clowd/Clowd.Squirrel/assets/114909797/0737eaaf-8e29-4c38-8bc4-b1969eb24b48)

Only the features of that version are written in all releases files. Something like this;

1.0.0 RELEASES Doc
`0638B9C43C6D646DF05E597FDE2F82426956A4A8 TestApp-1.0.0-full.nupkg 7376481`

1.0.1 RELEASES Doc
`F2108A90B0B2E1EB309289888745CCDEBE23FA68 TestApp-1.0.1-full.nupkg 7376480`

I didn't encounter any apparent problems. Could such use cause any problems?
As for why I did this, because with each new update, the release document gets bigger and bigger.

**Comment by caesay** [comment]
This is correct. your RELEASES file in each GitHub release should only have the nupkg's you upload in your release. However, the way you have it currently will not support delta updates. if this is important to you, please make sure you also upload a `TestApp-1.0.1-delta.nupkg` with your release, and include both the `-full` and the `-delta` in your RELEASES file.
