### ISSUE TITLE
Install date is always today

### ISSUE THREAD

**Issue by RandomEngy** [clowd/Clowd.Squirrel#197]
Using Squirrel 2.9.42, a user noticed that the "installed" date in Add/Remove Programs is always today, and not when the original install happened: https://github.com/RandomEngy/VidCoder/issues/1200

<img width="216" alt="image" src="https://github.com/clowd/Clowd.Squirrel/assets/9450861/8210a700-4543-480d-bb41-bb15a7f99a9c">

I checked the patch notes since that version and didn't see a fix listed. But I've also updated to 2.11.1 so I can see if it's still there on the next release.

**Comment by caesay** [comment]
This date is updated when you call `CreateUninstallerRegistryEntry`, and also automatically when the app is installed or updated. I had a quick look at VidCoder, and it doesn't look like you're calling this on app start in any place obvious, so the app was likely updated today.

**Comment by RandomEngy** [comment]
I can still reproduce this on Windows 11. The date is updated on launching the app. I only call CreateUninstallerRegistryEntry in the OnInitialInstall callback. I also have logging around it, but that logging is not hit.

The shortcut I'm using is:
`C:\Users\username\AppData\Local\VidCoder.Beta\VidCoder.exe`

Start in:
`C:\Users\username\AppData\Local\VidCoder.Beta\app-8.12.0`

Though that folder no longer exists, it's on 9.14 now.

**Comment by caesay** [comment]
In that case, my guess is that this (https://github.com/clowd/Clowd.Squirrel/blob/master/src/Squirrel/IUpdateManager.cs#L233) is getting hit when you check for updates, even though there are no updates available. As a work-around, you could do the update steps (check, download, apply) individually yourself, and not call this function if there are no updates available. As this library is being deprecated in favor of Velopack, and this is not a critical bug, I can't promise a fix.

**Comment by caesay** [comment]
Closing as wontfix since there is a workaround and this is not a critical bug
