### ISSUE TITLE
Can't detect AssemblyMetadata attribute in a SingleFile app

### ISSUE THREAD

**Issue by caesay** [clowd/Clowd.Squirrel#2]
Mono.Cecil can't load an exe produced by PublishSingleFile. Do we try to read the entry assembly by looking for the bundle offset  and parse the attribute? Probably not a great idea as these bundles might change significantly in future versions of dotnet.

It's also not possible to add the native SquirrelAwareApp entry to the version table (with rcedit or other) because this breaks the bundle. (see #1)

Perhaps we need a way to detect a Squirrel app that is a bit more universal. Reading exe manifest? Looking for a sidecar file (eg. `myapp.exe.squirrel`)?

**Comment by ComtelJeremy** [comment]
Just a thought, but can the attribute be added with rcedit, or similar? This is what I was planning on doing before noticing you fork. Watching your fork and work with interest, as we have been very sad about the state of Squirrel.

**Comment by caesay** [comment]
An entry in the assembly manifest can now be used to indicate a squirrel aware binary. This manifest can be read from single file apps.

For example:

```xml
<?xml version="1.0" encoding="utf-8"?>
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1">
  <SquirrelAwareVersion>1</SquirrelAwareVersion>
</assembly>
```
