### ISSUE TITLE
Issue with: "Reading SquirrelAwareVersion from assembly attribute is no longer supported."

### ISSUE THREAD

**Issue by simader** [clowd/Clowd.Squirrel#21]
Hi Caesy,

When there is a .net6 WPF Application with GenerateManifests=true in the .csproj, Squirrel Releasify will fail

	<GenerateManifests>true</GenerateManifests>

[ERRO] System.ArgumentException: There are no SquirreAwareApp's in the provided package. Please mark an exe as aware using the assembly manifest, or use the '--allowUnaware' argument to skip 
this validation and create a package anyway (at your own risk).
   at SquirrelCli.Program.<>c__DisplayClass4_0.<Releasify>b__8(String pkgPath, ZipPackage zpkg)
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, Func`2 releaseNotesProcessor, Action`2 contentsPostProcessHook) in C:\Source\Clowd\clowd-windows\modules\Clowd.Squirrel\s
rc\Squirrel\ReleasePackage.cs:line 120
   at SquirrelCli.Program.Releasify(ReleasifyOptions options)
   at SquirrelCli.CommandAction`1.Execute(IEnumerable`1 args)
   at SquirrelCli.CommandSet.Execute(String[] args)
   at SquirrelCli.Program.Main(String[] args)

If this setting is set to false everything works. 

If needed I can provide a sample

**Comment by caesay** [comment]
I am struggling to find MSDN documentation on this property (do you have any links to the documentation you can share?), but I assume it generates some kind of default application manifest and replaces the `<ApplicationManifest>app.manifest</ApplicationManifest>` option. In this case, we can't expect Squirrel to be able to detect the app - as we use the manifest to contain the SquirrelAwareVersion instead of an assembly attribute.

**Comment by caesay** [comment]
https://github.com/dotnet/docs-desktop/blob/a3b012ae9986291fe3238646dacc62d3c4da3daa/dotnet-desktop-guide/framework/wpf/app-development/building-a-wpf-application-wpf.md#manifest-generation

According to the docs, this property is for generating ClickOnce manifests for wpf applications. Can you explain why using ClickOnce and Squirrel together would be useful?

In any case, turning this on causes the <SquirrelAwareVersion> attribute to get moved into a sidecar file, `MyApp.dll.manifest`, while clickonce get's full ownership of `MyApp.exe.manifest`

**Comment by caesay** [comment]
After 59f151abbc62e844b7f8da22e1c62f88ea357d4a there is now 5 ways to specify SquirrelAwareVersion. Native versioninfo block, embedded manifest, external exe manifest, external dll manifest, or a `MyApp.exe.squirrel` sidecar file.
