### ISSUE TITLE
Squirrel not creating desktop and Start Menu shortcuts

### ISSUE THREAD

**Issue by wiggleforlife** [clowd/Clowd.Squirrel#27]
Thanks for the fork of Squirrel for .NET 6!
I'm porting an application to .NET 6 and this fork doesn't seem to be creating Start Menu and desktop shortcuts. It is properly installing everything into the `%localappdata%` folder. I am packing using the template (`Squirrel.exe pack --packName "YourApp" --packVersion "1.0.0" --packAuthors "YourCompany" --packDirectory "path-to/publish/folder"`) found in the README. I've tried on my almost fresh install of Windows 10 and someone else's heavily modified system. Any thoughts?

**Comment by remco1271** [comment]
Did you add the code from step 3 from the REAME.md to your project?
```cs
   public static int Main(string[] args)
   {
       SquirrelAwareApp.HandleEvents(
           onInitialInstall: OnInstall,
           onAppUpdate: OnUpdate,
           onAppUninstall: OnUninstall,
           onFirstRun: OnFirstRun);
           
       // ...
   }

   private static void OnInstall(Version obj)
   {
       using var mgr = new UpdateManager("https://the.place/you-host/updates");
       mgr.CreateUninstallerRegistryEntry();
       mgr.CreateShortcutForThisExe(ShortcutLocation.StartMenu | ShortcutLocation.Desktop);
   }
// ...
   ```

**Comment by caesay** [comment]
In order for shortcuts to be created automatically, the following must be true:
 - Your binary must be marked as SquirrelAware via assembly manifest
 - You must handle OnInstall and execute `CreateShortcutForThisExe` as remco mentioned.

If you are already doing those two things, the next thing to try is to run the following command in an installed app:

> %localappdata%\YourApp\Update.exe --createShortcut=YourApp.exe --shortcut-locations=Desktop

And then post the log file here (you can find it at at `%localappdata%\YourApp\Squirrel-Shortcut.log`)

If that still doesn't work, and you have a sample app, I am happy to take a look

**Comment by wiggleforlife** [comment]
I apologise for the inconvenience, I did indeed miss the `CreateShortcutForThisExe()` in the program. I'll test this now and hopefully get it working. Thanks @caesay for checking out our program and giving us further pointers!
