### ISSUE TITLE
Is it a big change to add older vcredist runtimes, like VS2013?

### ISSUE THREAD

**Issue by theresia-tobii** [clowd/Clowd.Squirrel#30]
Which we unfortunately have a third party dependency on for one of our applications.

I could even try my hand at a PR if you want.

**Comment by caesay** [comment]
It's not a huge change, I'd be happy for you send a pull request if you are interested!

The redist for 2015-2022 is all at the same download url and is fully backwards compatible. When installing, if your required version is more recent than the currently installed version, we just always install the latest version. 

To support older versions, we will need to allow different download URL's to be provided. This could be done by providing a new constructor in [VCRedistInfo](https://github.com/clowd/Clowd.Squirrel/blob/develop/src/Squirrel/RuntimeInfo.cs#L321), allowing a download url to be supplied (for both x86 and x64). An alternative (possibly cleaner way) would be to create a new class `LegacyVCRedistInfo` which derives from `VCRedistInfo` and just overrides the `GetDownloadUrl` method. 

You can find the details of the 2015-2022 behavior, as well as the download links and min-versions for older redists at this link: https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

**Comment by theresia-tobii** [comment]
Ok, I will give it a go this weekend.

**Comment by caesay** [comment]
I have added 2010-2013, if you need anything other than that feel free to send a PR

**Comment by caesay** [comment]
This is now released [in 2.7.79](https://github.com/clowd/Clowd.Squirrel/releases/tag/2.7.79-pre).
