### ISSUE TITLE
Log files for install?

### ISSUE THREAD

**Issue by RandomEngy** [clowd/Clowd.Squirrel#39]
Are there any log files written when the app install is happening? I'm having reports come in of people getting stuck and I need to figure out what's going on:

https://github.com/RandomEngy/VidCoder/issues/979

Using 2.7.98-pre.

**Comment by starkebn** [comment]
Are the log files written in some other folder? What the screenshot shows is what's there

**Comment by caesay** [comment]
If an error occurred extracting your package from the setup bundle, a MessageBox will be shown to the user with the error. If the package is extracted and run successfully, the log files are available at `%localappdata%\SquirrelClowdTemp`.
