### ISSUE TITLE
Package Naming question

### ISSUE THREAD

**Issue by Arcalise08** [clowd/Clowd.Squirrel#44]
In one of the recent updates it seems like packName has been deprecated in favor of PackId. So that brings up a question around the naming conventions here. For example a program named `Example Application`, Would work just fine as a program name. However that wouldnt work as a packId since no spaces are allowed within the packId. 

In that example we have a nuspec file that specifies the displayName but it seems to be ignored. When desktop shortcuts and uninstall triggers are ran, they are done without the space. I realize this is a pretty minor issue but I'm just wondering if I'm missing something

**Comment by caesay** [comment]
The argument `packName` has been renamed to `packId`, and has always required the name/id to have no spaces. It can have alphanumeric characters as well as dots and dashes. This is used for the nupkg id, as well as used for your app folder (`%localappdata%\packId`).

The `packTitle` argument was added to allow you to specify a display name with a space, and will be used for things like PE metadata and the uninstall entry in Apps & Features. 

More info here https://github.com/clowd/Clowd.Squirrel/issues/25.
