### ISSUE TITLE
Installer arguments

### ISSUE THREAD

**Issue by Arcalise08** [clowd/Clowd.Squirrel#51]
The documentation on the installer seems a little light. I realize this is a carry over from the original squirrel branch but I was wondering if there was any arguments I could pass to the installer to make it quietly install with no autostart after install.

**Comment by caesay** [comment]
Absolutely, the only docs I've updated is the readme, going through and re-doing all the other documentation is high on my list of priorities. 

`-s` or `--silent` will prevent any dialogs from showing, and if there are any prompts like "would you like to install .net?" it will auto-respond 'no'. This does not prevent autostart, however. I would be willing to accept a PR that adds a `--nostart` argument to setup if you need to prevent the first application run.

**Comment by Arcalise08** [comment]
I've added the argument `-noautostart` and submitted a PR for it. It works fine, However I have noticed squirrel tends to open the application for a moment during setup and then kill it.. It does the same thing when you uninstall it.

**Comment by caesay** [comment]
Thanks for your PR! I have not looked at it yet, but Squirrel starting the binary is expected. There are 5 "hooks" which will run your application at various points with different command line arguments. For most of them, you're expected to handle the event appropriately (eg. install application shortcuts) and then exit. 

This is covered in the quickstart guide in steps 2 and 3. 

Also can read more here 
https://github.com/clowd/Clowd.Squirrel/blob/develop/docs/using/custom-squirrel-events-non-cs.md and https://github.com/clowd/Clowd.Squirrel/blob/develop/docs/using/custom-squirrel-events.md although those docs are a little outdated.

**Comment by caesay** [comment]
If you do not want Squirrel to execute hooks, you should not mark your binary as "SquirrelAware" using the manifest.

**Comment by Arcalise08** [comment]
> If you do not want Squirrel to execute hooks, you should not mark your binary as "SquirrelAware" using the manifest.

Ahh that explains why im just now seeing this behavior. I recently converted an old winforms project to .net core and i was effected by an error in this repo that made it so it would not build if it wasnt squirrel aware. We dont use the hooks in this project at all and it seems like that error is fixed so i may revert back to being unware if this is the case.

**Comment by caesay** [comment]
You can use the `--allowUnaware` argument to revert back to previous behaviour, the only thing that's changed in terms of hook handling is that this is now an error by default.
