### ISSUE TITLE
UpdateManager.IsInstalledApp returning true for non-installed version when a different Update.exe is present in nearby folder

### ISSUE THREAD

**Issue by RandomEngy** [clowd/Clowd.Squirrel#63]
I have a portable version of VidCoder built as a WinRAR self-extracting EXE. It extracts all the program files to %localappdata%\Temp\RarSFX0 , then runs the EXE there. Inside VidCoder I call UpdateManager.IsInstalledApp to see if it was installed via Squirrel and it was returning `true` if there happened to be an `Update.exe` in the `%temp%` folder. Which I guess can happen because all kinds of programs write there.

https://github.com/RandomEngy/VidCoder/issues/1003

I can reorder the checks to fix this for VidCoder, but thought you might want to know.

**Comment by caesay** [comment]
Can you provide me with the value of `UpdateManager.AppDirectory` and `UpdateManager.AppId`?

**Comment by RandomEngy** [comment]
In this case `UpdateManager.IsInstalledApp` returns true, and it thinks that `UpdateManager.AppDirectory` is `C:\Users\david\AppData\Local\Temp` and that `UpdateManager.AppId` is `Temp`.

**Comment by caesay** [comment]
This is closed by fc0772816ab38cb5fcb0678a6bf5487fef7393ce, essentially more strict checking for the expected directory structure (eg. `app-`). It's not an amazing fix, but a carry over from the original Squirrel architecture. After #24 we'll have better ways to detect for installed apps.
