### ISSUE TITLE
Is it possible to use 4 components in the version number?

### ISSUE THREAD

**Issue by cpCr4zy** [clowd/Clowd.Squirrel#65]
Our application has four components in a version, like 5.10.13.661
I tried to specify them for a Squirrel (pack -v=5.10.13.661) and got the following exception:

`[ERRO] System.Exception: Invalid package version '5.10.13.661', it must be a 3-part SemVer compliant version string.
   at Squirrel.NuGet.NugetUtil.ThrowIfVersionNotSemverCompliant(String version) in ./NuGet/NugetUtil.cs:line 36   
   at SquirrelCli.PackOptions.Validate() in ./Options.cs:line 180
   at SquirrelCli.CommandAction`1.Execute(IEnumerable`1 args) in ./ValidatedOptionSet.cs:line 159
   at SquirrelCli.CommandSet.Execute(String[] args) in ./ValidatedOptionSet.cs:line 195
   at SquirrelCli.Program.Main(String[] args) in ./Program.cs:line 87`

I took a little look at the source code of the squirrel and noticed that it uses the code from 
https://github.com/zmarko/semver/tree/master/src

But judging by the author's comments this code should work with more complex constructions as well. For example
`version::Semver200_version v("1.2.3-alpha.1+build.no.123");`

Is there any way to use 4 components in the version number?

**Comment by caesay** [comment]
Regarding your example `1.2.3-alpha.1+build.no.123"`, this is semver2.0+ syntax and is not supported by the current c# implementation ([code here](https://github.com/clowd/Clowd.Squirrel/blob/develop/src/Squirrel/NuGet/SemanticVersion.cs)).

Both the old Squirrel and this fork do not support 4 part version strings (only 3-part) but this was a decision by the original author. There are no technical limitations preventing this library from supporting 4 part version strings, however I would be reluctant to allow this as in general I agree with the previous author and the semver guidelines (which state that 4 part versions are not allowed).

**Comment by caesay** [comment]
Closing this as there were no further comments and I do not have plans to support 4 part version strings at this time.
