### ISSUE TITLE
Cannot create HttpClientFileDownloader with Client Certificate.

### ISSUE THREAD

**Issue by belmonmi** [clowd/Clowd.Squirrel#66]
Sir/Madam,

Obsolete FileDownloader let me pass client certificate into constructor, new HttpClientFileDownloader doesn't have this option. Is there a different way to provide client certificate to UpdateManager? If not, can constructor that accepts client certificate to be added to HttpClientFileDownloader?

Thank you,
Michael.

**Comment by belmonmi** [comment]
Based on your source adding client certificate to HttpClient can be achieved very simple inside  HttpClientFileDownloader.CreateHttpClient() method. After HttpClientHandler instance is created the only thing what needs to be done is to check X509Certificate2 type of private member is assigned and add it to the ClientCertificates collection:

            if (m_Cert != null)
                handler.ClientCertificates.Add(m_Cert );

Add a private property m_Cert to HttpClientFileDownloader and constructor:

        private readonly X509Certificate2 m_Cert;

        /// <summary>
        /// .ctor
        /// </summary>
        /// <param name="inCert">instance of <see cref="X509Certificate2"/> if required</param>
        public HttpClientFileDownloader(X509Certificate2 inCert = null)
        {
            this.m_Cert = inCert;
        }

All changes are done in one file with no impact on the rest of functionality.
Thank you,
Michael.

**Comment by caesay** [comment]
Hi Michael, `HttpClientHandler.ClientCertificates` does not exist in .net4.6.1 (which this library supports). 

It is possible for you to deriving your own class and override `CreateHttpClient` as it is marked virtual. 

Example: 

```cs
public class MyFileDownloader : HttpClientFileDownloader
{
    protected override HttpClient CreateHttpClient(string authorization, string accept)
    {
        var handler = new HttpClientHandler() {
            AllowAutoRedirect = true,
            MaxAutomaticRedirections = 10,
            AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate,
        };

        handler.ClientCertificates.Add(____INSERT_YOUR_CERTIFICATE____);

        var client = new HttpClient(handler, true);
        client.DefaultRequestHeaders.UserAgent.Add(UserAgent);

        if (authorization != null)
            client.DefaultRequestHeaders.Add("Authorization", authorization);

        if (accept != null)
            client.DefaultRequestHeaders.Add("Accept", accept);

        return client;
    }
}
```

I may look to improve this in the future, but closing this issue as there is a valid workaround in place. Feel free to re-open this issue if you believe there is more to discuss.

**Comment by belmonmi** [comment]
caesay,

Thank you very much, this is great idea and very easy to implement.

Michael.
