### ISSUE TITLE
Taskbar pinning on Windows 11

### ISSUE THREAD

**Issue by caesay** [clowd/Clowd.Squirrel#69]
I have not seen this issue myself but it was reported on Discord that the AppUserModelId is not working correctly on Windows 11. After an update, clicking a pinned shortcut launches the app, but a second icon appears (the new process does not get grouped with the shortcut). This seems to be the case even if `SetProcessAppUserModelId` is used in OnEveryRun. 

Another possible issue on Win11 is that the Uninstaller DisplayVersion does not seem to be updated. I am wondering if this is a failure to update the registry key, or if Win11 UI is caching this somewhere and failing to update the UI until a restart.

**Comment by remco1271** [comment]
Did a quick try on windows 11
```
[DllImport("shell32.dll")]
public static extern void GetCurrentProcessExplicitAppUserModelID([Out(), MarshalAs(UnmanagedType.LPWStr)] out string AppID);
```
The script in my program:
```
private void OnAppRun(SemanticVersion version, IAppTools tools, bool firstRun)
{
    string AppID = string.Empty;
    NativeMethods.GetCurrentProcessExplicitAppUserModelID(out AppID);

    AppIDReport(AppID, version, false);
    tools.SetProcessAppUserModelId();
    AppIDReport(AppID, version, true);
}

private void AppIDReport(string str, SemanticVersion version, bool afther)
{
    if (str == null)
    {
        str = "!NULL!";
    }
    if (afther)
    {
        Log.Information("New AppID: " + str + " Version: " + version.ToString());
    }
    else
    {
        Log.Information("Old AppID: " + str + " Version: " + version.ToString());
    }
}
```
But I see that OnAppRun is only run during the install of the program.
On install the Log reports:

> Old AppID: !NULL! Version: 1.0.37
> New AppID: com.squirrel.CanBus_Monitor.CanBusMonitor Version: 1.0.37

On the next run of the program it doesn't run the OnAppRun and the AppID is NULL
My project is running .NET 6.0

**Comment by caesay** [comment]
I have fixed the OnAppRun hook [in 2.9.23-gc8da1a](https://github.com/clowd/Clowd.Squirrel/releases/tag/2.9.23-gc8da1a) but I have not confirmed that it fixes the shortcut pinning issue.

**Comment by remco1271** [comment]
The pinning for Windows 11 is now working

**Comment by caesay** [comment]
Thanks for looking into this @remco1271 !
