### ISSUE TITLE
UpdateManager.RestartApp() not raising the Application.ApplicationExit event

### ISSUE THREAD

**Issue by Hyrius** [clowd/Clowd.Squirrel#71]
I'm using the **ApplicationExit event** to remove the **TrayIcon** of my application, otherwise it just stays there until the cursor hovers over it.

**Application.ApplicationExit += new EventHandler(OnApplicationExit);**

        public void OnApplicationExit(object sender, EventArgs e)
        {
            TrayIcon.Visible = false;
        }

Anyway, I need call **OnApplicationExit()** manually before **UpdateManager.RestartApp()** every time the software updates, as the event is never raised. I know it's the framework itself that is supposed to raise the event, but any idea why it isn't working with **RestartApp()**?

**Comment by caesay** [comment]
Squirrel does not know what UI framework you are using, so can't call any shutdown functions. Calling `RestartApp` will exit via `Environment.Exit` which does not allow any graceful cleanup (like these events). 

If you need to do clean-up before the app exits, you should use `UpdateManager.RestartAppWhenExited` instead. This function sets up the restart, but will not exit your app. Example:

```cs
async Task restartMyApp() 
{
    // Tell Squirrel to restart my app when this process terminates
    await UpdateManager.RestartAppWhenExited();
    // Clean up tray icon
    TrayIcon.Visible = false;
    // Gracefully shutdown WPF
    Application.Current.Shutdown();
}
```

**Comment by Hyrius** [comment]
That's great to know. Thank you!
