### ISSUE TITLE
Package Manager - 'Releasify' is an invalid command

### ISSUE THREAD

**Issue by Reddgum** [clowd/Clowd.Squirrel#76]
Perhaps I'm missing something, but running the command:

PM>Squirrel --releasify 

and

PM>Squirrel --releasify MyPackage.2.100.0.nupkg 

Produce a scrolling PM window with usage info, declaring --releasify is not a valid command (even though it shows in the list of valid commands...)

**Comment by caesay** [comment]
The command is `releasify` not `--releasify`.  Try:

> Squirrel.exe releasify -p Mypackage.2.100.0.nupkg

The command line has changed quite substantially, please review it carefully if you are migrating from the old Squirrel.

**Comment by Reddgum** [comment]
Hey thanks for the response, Caelan.

I was following what the Nuget PM help output console window printed out --
it still shows using the old '--' method.
The good news is that I finally found the source to an auto-updater that I
wrote a couple years back; lost because it was on a system where the SSD
died, but fortunately I'm a bit of a nut when it comes to making
geographically distributed backups and found the source late yesterday on
one of my portable backup drives in my storage locker, lol.

When this crazy part of my project is done, I'm going to revisit Squirrel.


Cheers

-Mike
