### ISSUE TITLE
Remote release File is empty or corrupted

### ISSUE THREAD

**Issue by mitjaahlin** [clowd/Clowd.Squirrel#80]
hi,
a third of our users are experiencing the following error...

![image](https://user-images.githubusercontent.com/26851656/170044605-e00d0fb1-3495-4f26-ab12-4c121a58ab1a.png)

Any idea what may be causing this? The file is not corrupted.
This is how our app checks for updates:

```cs
using (var mgr = new UpdateManager(Constants.UpdateDir))
{
  var newVersion = await mgr.CheckForUpdate();

  if (newVersion != null && newVersion.ReleasesToApply.Any())
  {
    return (true, newVersion.ReleasesToApply.First().Version.Version);
  }
}
```
Thanks

**Comment by caesay** [comment]
The error specifies that the RELEASES file is either missing, empty, or invalid. Please verify that `Constants.UpdateDir/RELEASES` exists, and share it's contents here.

**Comment by caesay** [comment]
Also, you should not use `newVersion.ReleasesToApply.First().Version.Version` if your goal is to determine what the latest available version is. You should instead check `newVersion.FutureReleaseEntry.Version`

**Comment by mitjaahlin** [comment]
thanks for the response, the file was indeed corrupted at the client pc...
