### ISSUE TITLE
Exception: There are no SquirreAwareApp's in the provided package

### ISSUE THREAD

**Issue by WuYin-Lyu** [clowd/Clowd.Squirrel#81]
When using Releasify to pack my project. I get an exception: There are no SquirreAwareApp's in the provided package.
Squirrel is looking into "lib\" folder for the SquirrelAwareValue. In most framework dependent app, the SquirrelAwareValue will be in "lib\%framework%\" folder. Is it better to search SquirrelAwareValue in "lib\%framework%\" folder.

**Comment by caesay** [comment]
You can place your app files into any lib directory. `lib/blah` is valid, and so is `lib/framework`. 

The reason you are getting this message is because you have not marked any executables as SquirrelAware by following the readme and adding the required entry to your application manifest. 

Please review the Readme, confirm you have completed the steps and re-open an issue if you are still having problems.

**Comment by WuYin-Lyu** [comment]
I do add <SquirrelAwareVersion xmlns="urn:schema-squirrel-com:asm.v1">1</SquirrelAwareVersion> in my manifest. And pack it in my nupkg file. The path in nupkg file is "\lib\netcoreapp3.1\MyApp.dll.manifest". 
I still get this error

**Comment by ypicard** [comment]
How did you fix this @WuYin-Lyu ?

**Comment by caesay** [comment]
Hi, @ypicard, please review the main `readme.md`. This fork does not support the `AssemblyMetadata` attribute, you must mark your binary as Squirrel aware by following the quick-start guide and adding to your assembly manifest.

**Comment by ypicard** [comment]
All right, I have not found where it is specifically said that `AssemblyMetadata` is not supported, sorry. I am quite new to the Windows / c# / dotnet world and did not know about the difference.

In the readme, the following is stated:

> Add SquirrelAwareVersion to your assembly manifest to indicate that your exe supports Squirrel.
```
<?xml version="1.0" encoding="utf-8"?>
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1">
  <SquirrelAwareVersion xmlns="urn:schema-squirrel-com:asm.v1">1</SquirrelAwareVersion>
</assembly>
```

I am currently working on a c# project. Would you be able to tell me where I am supposed to add this specifically? in the `.csproj` file? With what syntax? It seems to require `ItemGroup`, `Property` or some other nesting to be valid.

Thank you very much for the help.

**Comment by caesay** [comment]
### If you are using Visual Studio

1. Right click your project in the solution explorer and add a new item
    ![image](https://user-images.githubusercontent.com/1287295/172735236-1805d43c-7af3-47a7-9893-ee7645408eb6.png)
2. Choose to add a new Application Manifest File
   ![image](https://user-images.githubusercontent.com/1287295/172735252-d1fd5231-9b24-4431-9379-4ac79b43f1fc.png)
3. Replace the contents of that file with the text from the readme
   ```xml
   <?xml version="1.0" encoding="utf-8"?>
   <assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1">
     <SquirrelAwareVersion xmlns="urn:schema-squirrel-com:asm.v1">1</SquirrelAwareVersion>
   </assembly>
   ```

### If you are not using Visual Studio
1. Create a new file called `app.manifest` in the same directory as your `.csproj` file. 
2. Set the contents of the file to the xml shown above
3. Add the following lines to your csproj:

   ```xml
   <PropertyGroup>
     <ApplicationManifest>app.manifest</ApplicationManifest>
   </PropertyGroup>
   ```

**Comment by knd775** [comment]
My problem is that when using a single file self-contained executable, this doesn't work. The executable itself doesn't use my manifest, but the embedded dll does. Any workarounds or other options?

**Comment by caesay** [comment]
Alternatively, for those who do not wish to use an assembly manifest, you can create a file called `YourFile.exe.squirrel` in your build output directory and set the contents of the file to `1`.

**Comment by rzamponiAtIgt** [comment]
Is there a specific reason why you removed the possibility to simply set the AssemblyMetadataAttribute?
In our company we used a custom SDK to create AssemblyMetadataAttributes with the required squirrel.windows properties SquirrelAwareVersion, SquirrelAppName and SquirrelInstallerOutputPath during build. While the usage of the <YourFile.exe.squirrel> file is a valid workaround it feels a bit clumsy in comparison to the attribute.
