### ISSUE TITLE
Running Setup.exe pops up a console window

### ISSUE THREAD

**Issue by solita-tuomaska** [clowd/Clowd.Squirrel#82]
When running the Setup.exe (either for the first time or not) it briefly flashes a console window for Squirrel.exe during the installation process. This could hurt user confidence especially with the red error text appearing in the window. Is this a known issue and/or are there workarounds to make it not appear? Attached a screenshot that I managed to catch before it disappeared with project details hidden:

![squirrel-window](https://user-images.githubusercontent.com/83633134/170993412-fc32d59c-6bc5-4ebf-816e-67ec74c80ff7.png)

Version used: 2.9.40

This could be related to #75 but the description sounds different enough.

**Comment by caesay** [comment]
Thanks for reporting this - I have not seen this. Something looks seriously broken here, as the screenshot you are showing here is the Squirrel.exe package builder, and that should not even be present when running setup.

Can you tell me a bit more about how you are building your update packages? are you copying Squirrel.exe into them? Can you share the command line you used to create the package?

**Comment by solita-tuomaska** [comment]
Thanks for the quick response! It pointed us to the right direction, for some reason in our app's .nuspec file we were indeed packaging the Squirrel.exe. I guess we never noticed this being a mistake with older Squirrel.Windows versions or if it was added there for a reason.

In any case problem solved, thank you

**Comment by solita-tuomaska** [comment]
Found the reason why we had the Squirrel.exe packed in, this is from the Squirrel (both this and original) FAQ:

> I've Distributed a Broken Copy of Update.exe. How can I fix this?
> Sometimes, you might ship a broken copy of Update.exe that succeeds the initial install, but doesn't do what you want for some reason. To fix this, you can force an update of the Update.exe by including a copy of Squirrel.exe in your app update package. If Squirrel sees this, it will copy in this latest version to the local app installation.

Now I'm wondering if this functionality still exists in this fork?

**Comment by caesay** [comment]
Yes this behavior is the default in this fork. Update.exe will be updated every time you update your app. Check the main readme for more info.

**Comment by solita-tuomaska** [comment]
Oh I see, thank you.
