### ISSUE TITLE
Install/bootstrap new runtimes during updates

### ISSUE THREAD

**Issue by caesay** [clowd/Clowd.Squirrel#9]
A user might ship a net5 app, and subsequently publish an update to net6 - but this is impossible with Squirrel as the runtime bootstrapping is done by Setup.exe which is not preserved.

Now that Update.exe is fully self-contained, we could move the runtime bootstrapping to Update.exe (or even Squirrel.dll) to allow new runtimes to be installed during updates. 

We now have the capability to check the app manifest for the SquirrelAwareVersion attribute (and this should probably be the preferred way going forward as it works uniformly for native apps, C# apps, and single file apps). 

Perhaps the runtime dependency could also be read from the manifest (<SquirrelRuntime>net6</SquirrelRuntime>), and we can check binaries during updates to confirm that all the required runtimes are indeed installed. This could also allow us to automatically update minor versions (eg. 5.0.6 to 5.0.7) if an app requests it.

**Comment by caesay** [comment]
Just a thought: the installer can be run silently, and will install on top of the old version, so instead of moving bootstrapping to C# we could add helper methods to make it easier to download, exit app, and start the setup to install a new framework. Right now Setup.exe just fast-exits, but perhaps it should support some additional command line arguments to check for missing dependencies etc.

**Comment by simader** [comment]
Hi caesey,
I also expirenced, that on new installation the download of the .net6 runtime started automatically. 
However on updates the following link is opened: https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime

Is it possible to have the same logik on install and update?

**Comment by caesay** [comment]
Installing new versions of runtimes during updates was never a feature of the old Squirrel, but it's something I am considering adding in the next release which is why this issue is open as an enhancement.

**Comment by caesay** [comment]
Commit 791f34b69e77bf4939e83e4e6aa07be986b0f406 and 160373ec9567ec1c306e2b48ba6be7c93ddfa25b make it possible to install new runtimes while updating your app. It is not fully automatic. 

If you were planning an update from .net5 to .net6, for example, you'd need to first push the below code on .net5. It would allow you to install net6 before your users get get the update. 

I may revisit this later to see if it can be further automated, but I suspect not - because it requires the user to accept a UAC prompt while installing .net, and this should not be unexpected (eg. the user needs to be interacted with first)

```cs
private static async void UpdateMyApp()
{
    var net6 = Runtimes.DOTNET6_X64;
    var net6installed = await net6.CheckIsInstalled();
    // ask user if they would like to install net6 if it is not already installed
    if (!net6installed)
    {
        if (MessageBoxResult.Yes == MessageBox.Show("Would you like to install net6?", "Update", MessageBoxButton.YesNo))
        {
            // install net6 before we install our update
            var instPath = Path.GetTempFileName() + ".exe";
            await net6.DownloadToFile(instPath);
            await net6.InvokeInstaller(instPath, isQuiet: true);
        }
        else
        {
            // do not install your app update until net6 is installed
            return;
        }
    }

    // net6 is now installed, you can update normally
    using var mgr = new UpdateManager("https://the.place/you-host/updates");
    var newVersion = await mgr.UpdateApp();

    // optionally restart the app automatically, or ask the user if/when they want to restart
    if (newVersion != null)
    {
        UpdateManager.RestartApp();
    }
}
```

**Comment by theresia-tobii** [comment]
The problem with needing to add code to do this in the app itself is that users might miss that particular version if the app is not run very often. I would really like to see this being part of the update.exe and automated.

**Comment by caesay** [comment]
Workaround suggested by @theresia-tobii for how to ensure that the necessary runtime is installed prior to updating to net5 or higher:

> * The old app fetches updates from "url1".
> * Add an update that uses net framework like before but clowd.squirrel with the workaround from [Install/bootstrap new runtimes during updates #9](https://github.com/clowd/Clowd.Squirrel/issues/9).
> * Make this update fetch releases and updates from a new URL so that it will essentially be the last update from the old URL causing it to never be skipped in the update chain.
> * So now any new updates requiring the new framework will be fetched from the new URL and thus only be enabled from that last version that ensures the runtimes are installed.

**Comment by caesay** [comment]
The required runtime dependencies is now stored in the nuspec metadata, and can be checked during the update procedure.

Because Squirrel has no updating UI, updates are often undertaken in the background by applications using the C# SDK. A UAC dialog should not appear without a warning to the user first, and I don't love the idea of changing the behaviour in a way that could result in an unexpected dialog during an update while using the SDK. 

Squirrel could also benefit from a helper class/functions allowing applications to explicitly show an update request prompt to the user if a dependency is missing. As long as it's opt-in, this could make updating to a new framework relatively straight-forward. 

Example

```cs
using var manager = new UpdateManager(...);
var updateInfo = await manager.CheckForUpdate();
await manager.DownloadReleases(updateInfo.ReleasesToApply);

if (await manager.VerifyRuntimesInstalled(updateInfo, promptUserIfRuntimeMissing: true)) { // <-- PROPOSED FUNCTION
    await manager.ApplyReleases(updateInfo)
}
```

And an optional overload to `UpdateApp` could be useful too:

```cs
using var manager = new UpdateManager(...);
await manager.UpdateApp(promptUserIfRuntimeMissing: true);
```

As well as a new command line option for `Update.exe`.

**Comment by caesay** [comment]
Closing because I am not planning on progressing this further unless there is need. There are workarounds in place for installing frameworks during updates, and self contained apps exist.

**Comment by caesay** [comment]
After 02b5b6 users will be automatically prompted to install missing app dependencies when the app is started.
