### ISSUE TITLE
How are dependencies installed?

### ISSUE THREAD

**Issue by xmln17** [clowd/Clowd.Squirrel#91]
I recently updated my Application from .Net 5 to .Net6. I did that update also in my Command for Squirrel package generation but as soon as an User who does not currently have .Net 6 installed updates my Application a Messagebox is showing up
`To run this application, you must install missing frameworks for .NET. The Framework 'Microsoft.NETCore.App Version 6.0.0 was not found` (my project uses Winforms).

All my projects are having depencies to `<TargetFramework>net6.0-windows</TargetFramework>`.
I tried to take a look into the source code but it is hard to find the cause (either on my or your side) of that behavior. As far as i know the .Net Desktop Runtime includes the standard one for consoles. Do you have an idea what caused this?

**Comment by caesay** [comment]
As mentioned in the main readme, you must use the `-f` argument to install one or more external dependencies. Please review the quickstart guide (specifically step 5 & 6) for more info.

**Comment by caesay** [comment]
I just re-read your issue. To clarify, if you are looking for external dependencies to be installed when users run Setup.exe, this is achieved with the `-f` argument. 

If you are already using Clowd.Squirrel and are updating from net5 to net6, and are looking for Squirrel to also update the runtime, this is only supported by Squirrel 3.x which is still in pre-release. 

A work-around exists for Clowd.Squirrel 2.x and was discussed at this pinned issue https://github.com/clowd/Clowd.Squirrel/issues/9

**Comment by xmln17** [comment]
Thank for you fast reply and the mentioned work-around. I already use the `--framework` argument when creating the package with Clowd.Squirrel. I just replaced the -`-framework "net5" with "net6"`. If I am understanding you correctly, updating the runtime is a feature that comes with the next release so this is fine for me as a solution.
