### ISSUE TITLE
The installer does not support Chinese character files

### ISSUE THREAD

**Issue by ohzxc** [clowd/Clowd.Squirrel#92]
Clowd.Squirrel 2.9.40 
VS 2022
.Net Framework 4.6.1

There is a problem when installing
![image](https://user-images.githubusercontent.com/2950068/174736978-90797a13-3da6-4a4e-904b-3107d30ccbe9.png)

Renaming the file is a temporary solution
![1655794808(1)](https://user-images.githubusercontent.com/2950068/174736871-3ce85d78-906a-4c47-bb09-85c687e3b5aa.jpg)

**Comment by caesay** [comment]
There is a related issue where the installer will fail if the windows username has unicode characters in it: https://github.com/ppy/osu/issues/18369#issuecomment-1159474093

Would you be able to provide a sample repository on GitHub that replicates the issue? If so, I'd be happy to take a look at it.

**Comment by ohzxc** [comment]
> I believe I have fixed this issue in [release 2.9.42](https://github.com/clowd/Clowd.Squirrel/releases/tag/2.9.42). Please test this fix and let me know if your issue is resolved. If something is still not working, please re-open this issue.

I tried [2.9.42](https://github.com/clowd/Clowd.Squirrel/releases/tag/2.9.42). The Error " invalid character sequence " has been fixed, but filename is not as expected

I publish a [demo repository](https://github.com/ohzxc/installtest)

### my file
![image](https://user-images.githubusercontent.com/2950068/174962944-2b172815-3dfd-4cbe-9c44-e277656a9f5c.png)

### after install
 
![1655880754(1)](https://user-images.githubusercontent.com/2950068/174963276-82a6e18d-aa0c-49b1-bc98-59dcd0e4317b.jpg)

**Comment by caesay** [comment]
I built and installed the sample app you provided and the installed file had the correct file name. Can you please share the Windows version you are building the release and installing on? 

Also can you please provide a sample `.nupkg` file that I can take a look at?

![image](https://user-images.githubusercontent.com/1287295/175800547-e0c9d5b8-ec61-4f1b-a6ad-31c7cf36d9e7.png)

**Comment by ohzxc** [comment]
Maybe the problem has something to do with the way of packing  ([.csproj file](https://github.com/ohzxc/installtest/blob/46b344870b92ad356ac39b3c5a7e45691caf0fb8/installtest/installtest.csproj#L123)). I'm not sure

![image](https://user-images.githubusercontent.com/2950068/175804236-4a790f0b-bcc3-4f13-b337-2e913e2933cb.png)

[.nupkg file ](https://github.com/ohzxc/installtest/tree/main/installtest/Publish)

![image](https://user-images.githubusercontent.com/2950068/175803856-b2803b82-b377-4a92-b06f-c7317ca6f9cd.png)

The same PC building and installing
windows 11 pro workstations  21H2
![image](https://user-images.githubusercontent.com/2950068/175803597-444dc07e-dfda-47e7-885c-757949f36783.png)

**Comment by caesay** [comment]
So the characters were corrupted while creating the zip file. Is your machine x64 or arm64? Can you share the build log?

On my PC the files are compressed successfully using 7za.exe which seems to handle the encoding of characters correctly but I am wondering if that is failing for you and it is falling back to using SharpCompress to create the package.

**Comment by ohzxc** [comment]
Windows 11 x64
build log looks good
```
1>  installtest -> D:\Repos\installtest\installtest\bin\Debug\installtest.exe
1>  [INFO] NugetConsole: Starting to package '%localappdata%\SquirrelClowdTemp\tempa\installtest.nuspec'
1>  [INFO] NugetConsole: Successfully created package '%localappdata%\SquirrelClowdTemp\tempa\installtest.1.0.2.nupkg'.
1>  [INFO] Program: Creating release for package: D:\Repos\installtest\installtest\Publish\installtest.1.0.2.nupkg
1>  [INFO] ReleasePackage: Creating release package: D:\Repos\installtest\installtest\Publish\installtest.1.0.2.nupkg => D:\Repos\installtest\installtest\Publish\installtest-1.0.2-full.nupkg
1>  [INFO] ReleasePackage: Removing unnecessary data
1>  [INFO] ReleasePackage: No release notes found in %localappdata%\SquirrelClowdTemp\tempc\installtest.nuspec
1>  [INFO] Program: There are 1 SquirrelAwareApp's. Binaries will be executed during install/update/uninstall hooks.
1>  [INFO] Program:   Detected SquirrelAwareApp 'installtest.exe' (arch: x86)
1>  [INFO] Program: Package Architecture (detected from SquirrelAwareApp's): x86
1>  [INFO] Program: Creating 1 stub executables
1>  [INFO] EasyZip: Compressing '%localappdata%\SquirrelClowdTemp\tempc' to 'D:\Repos\installtest\installtest\Publish\installtest-1.0.2-full.nupkg' using 7z...
1>  [INFO] Program: Creating Setup bundle
1>  [INFO] Program: Setup bundle created at 'D:\Repos\installtest\installtest\Publish\installtestSetup.exe'.
1>  [INFO] Program: Done
```

**Comment by ohzxc** [comment]
Related to system language.
Check "[Use Unicode UTF-8](https://stackoverflow.com/questions/56419639/what-does-beta-use-unicode-utf-8-for-worldwide-language-support-actually-do)" in system region settings, solved this problem.

or [add 7z Parameters "cu=on"](https://news.ycombinator.com/item?id=9388497) (untested)

Thank you for your reply

**Comment by caesay** [comment]
Hi, thanks for that info. I do not have this box checked and it still works for me so I am still unable to reproduce the issue. I am guessing that 7z is using an incompatible codepage to encode the zip for you and checking that box changed the code page to 65001 (UTF-8). 

If you are willing to do some additional testing, could you turn that box off and let me know what the following registry keys are?
 - Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nls\CodePage\OEMCP
 - Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nls\CodePage\ACP

Also, could you try deleting 7z.exe and doing a new build, Squirrel will use the C# compression and I want to see if this also has an issue or if it's just 7z?

I am going to re-open this issue to track the following:
 - 7z commands should be updated to force utf-8 with the [`-mcp=65001` and `-mcu=on` parameters](https://sevenzip.osdn.jp/chm/cmdline/switches/method.htm)
 - Set SharpCompress ArchiveEncoding to UTF-8

**Comment by caesay** [comment]
As SharpCompress did not have an issue either way, I have removed 7z from Squirrel in 26f55e95a451fcef3f95c3dc389bb8ea9c373405 to resolve this issue.
