### ISSUE TITLE
Bad Image exception when running installer on Win7 SP1 w/ ESU

### ISSUE THREAD

**Issue by caesay** [clowd/Clowd.Squirrel#98]
When running the setup on a Win7 SP1 w/ Year3 ESU package, a bad image exception (0xc000007b) appears when running Update.exe:

![image](https://user-images.githubusercontent.com/1287295/179310535-b1b4d32d-c4a9-4fee-82b2-e914c5a94aea.png)

This should either show a "This operating system is not supported" message, or we need to try and figure out what is causing the Updater to fail to launch. This year is the last year of ESU (ending on January 2023) so I'm not sure much time should be invested into fixing this; it might be good enough to just update the operating system check in Setup.cpp to mandate >= win 8.1 or even >= win 10 because the 8.1 end of life is also January 2023.

**Comment by ohzxc** [comment]
I got a different installation error on Win7 Professional x64 SP1

![image](https://user-images.githubusercontent.com/2950068/179353275-49870f3d-6409-44c4-b166-4278d6d085b1.png)
![image](https://user-images.githubusercontent.com/2950068/179353365-7d2117b4-3f57-43dc-b068-ffb9973937ae.png)

My solution
1. Put api-ms-win-core-winrt-l1-1-0.dll into C:\windows\syswow64\
2. [Install system patch Windows6.1-KB3063858-x64.msu](https://github.com/dotnet/core/issues/6976)

**Comment by ohzxc** [comment]
Using Squirrel v2.9.42. It's a customer's computer, and not installed ESU Year3.

> @ohzxc Does your version of Win7 have ESU Year3 installed? also what version of Squirrel are you using? Theoretically the issue you mentioned should be fixed in dotnet 6.0.3 [dotnet/runtime#63533](https://github.com/dotnet/runtime/pull/63533) which was used to compile Squirrel v2.9.42

**Comment by caesay** [comment]
I was unable to reproduce either of the above issues on a Win7 machine with ESU Year3 installed. I also tested win8.1 and didn't run into any problems. 

I am closing this issue as everything appears to be working on a fresh machine which is up to date with the latest updates from Microsoft. I don't plan to do anything further to support these operating systems but would accept a PR if someone else wishes to improve win7 compatibility.
