### ISSUE TITLE
Installed app size apparently multiplied by 6

### ISSUE THREAD

**Issue by Mourad57** [clowd/Clowd.Squirrel#99]
Hello

We have a wpf app that we package so far using squirrel 2.0.1
When installed, the app shows a size usually around 334mb under windows programs

We tried to migrate to clowd.squirrel and now the size shown is something around 2gb, 6 times above the expectation.

Nothing have significantly changed during the migration, only small adaptations to the clowd squirrel signatures in app.xaml.cs

Any idea what can be the issue ?

our wpf app is .net48

**Comment by caesay** [comment]
Thanks for trying this fork! The calculation in the registry is set by Squirrel, it's not calculated by the operating system. Squirrel.Windows sets the registry size to the size of the compressed package (eg. the same size as the .nupkg file), but this is a lie. In this fork I try to estimate the app size a little more accurately. 

You can see how this fork of Squirrel calculates the size here: https://github.com/clowd/Clowd.Squirrel/blob/develop/src/Squirrel/UpdateManager.InstallHelpers.cs#L60
